image: docker:stable

services:
   - name: docker:dind
  
variables:
  DOCKER_HOST: tcp://192.168.80.26:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
- build

build_and_push_image:
  stage: build
  tags: ['sa']
  before_script:
  - wget https://github.com/buildpacks/pack/releases/download/v0.18.0/pack-v0.18.0-linux.tgz
  - tar xvf pack-v0.18.0-linux.tgz
  - rm pack-v0.18.0-linux.tgz
  script:
  - echo "$GITLAB_PASSWORD" | docker login registry.gitlab.com --username "$GITLAB_USER" --password-stdin
  - ./pack build registry.gitlab.com/maaciekk/bmi-calculator-app --builder gcr.io/buildpacks/builder:lastest -e "GOOGLE_ENTRYPOINT=python app.py" --publish
